package integration;

import io.github.jtestkit.joot.JootContext;
import io.github.jtestkit.joot.test.fixtures.tables.pojos.Author;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static io.github.jtestkit.joot.test.fixtures.Tables.AUTHOR;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * TDD tests for nullable fields handling.
 * PHILOSOPHY: By default, generateNullables=TRUE (production-like objects).
 * Minimalist mode: generateNullables=FALSE (only NOT NULL fields).
 */
class NullableFieldsTest extends BaseIntegrationTest {
    
    private JootContext ctx;
    
    @BeforeEach
    void setup() {
        ctx = JootContext.create(dsl);
    }
    
    @Test
    void shouldGenerateNullableFieldsByDefault() {
        // ACT: Create Author without any flags (default behavior)
        Author author = ctx.create(AUTHOR, Author.class).build();
        
        // ASSERT: Both NOT NULL and nullable fields are generated (default=true)
        assertThat(author.getName()).isNotNull();     // NOT NULL field
        assertThat(author.getCountry()).isNotNull();  // nullable field (generated by default!)
    }
    
    @Test
    void shouldSkipNullableFieldsInMinimalistMode() {
        // ACT: Disable nullable generation on builder
        Author author = ctx.create(AUTHOR, Author.class)
            .generateNullables(false)
            .build();
        
        // ASSERT: NOT NULL field is generated, nullable field is null
        assertThat(author.getName()).isNotNull();
        assertThat(author.getCountry()).isNull();  // Skipped in minimalist mode
    }
    
    @Test
    void shouldRespectExplicitNullEvenWithDefaultGeneration() {
        // ACT: Explicitly set nullable field to null despite default generateNullables=true
        Author author = ctx.create(AUTHOR, Author.class)
            .set(AUTHOR.COUNTRY, null)  // Explicit null should win
            .build();
        
        // ASSERT: Explicit null is respected
        assertThat(author.getName()).isNotNull();
        assertThat(author.getCountry()).isNull();
    }
    
    @Test
    void shouldSupportGlobalMinimalistMode() {
        // ACT: Set global generateNullables=false on context
        ctx.generateNullables(false);
        
        Author author = ctx.create(AUTHOR, Author.class).build();
        
        // ASSERT: Global setting applies
        assertThat(author.getName()).isNotNull();
        assertThat(author.getCountry()).isNull();
    }
    
    @Test
    void shouldAllowBuilderOverrideOfGlobalSetting() {
        // ACT: Global is false, but builder overrides to true
        ctx.generateNullables(false);
        
        Author author = ctx.create(AUTHOR, Author.class)
            .generateNullables(true)  // Override global
            .build();
        
        // ASSERT: Builder override wins
        assertThat(author.getName()).isNotNull();
        assertThat(author.getCountry()).isNotNull();
    }
    
    @Test
    void shouldWorkWithRecordBuilder() {
        // ACT: Create Author Record (default generateNullables=true)
        var record = ctx.createRecord(AUTHOR).build();
        
        // ASSERT: Both fields are generated by default
        assertThat(record.getName()).isNotNull();
        assertThat(record.getCountry()).isNotNull();
    }
}

