package integration;

import io.github.jtestkit.joot.JootContext;
import io.github.jtestkit.joot.test.fixtures.tables.records.AuthorRecord;
import io.github.jtestkit.joot.test.fixtures.tables.records.BookRecord;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static io.github.jtestkit.joot.test.fixtures.Tables.AUTHOR;
import static io.github.jtestkit.joot.test.fixtures.Tables.BOOK;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * TDD Step 2.2.1: RecordBuilder public API tests
 * Tests creation of jOOQ Records (alternative to POJO API)
 */
class RecordBuilderTest extends BaseIntegrationTest {
    
    private JootContext ctx;
    
    @BeforeEach
    void setup() {
        ctx = JootContext.create(dsl);
    }
    
    @Test
    void shouldCreateRecordWithAutoGeneratedFields() {
        // ACT: Create Author as Record
        AuthorRecord record = ctx.createRecord(AUTHOR).build();
        
        // ASSERT: Record is created with auto-generated values
        assertThat(record).isNotNull();
        assertThat(record.getId()).isNotNull();
        assertThat(record.getName()).isNotNull();  // auto-generated
        
        // ASSERT: Record exists in DB
        AuthorRecord fromDb = dsl.selectFrom(AUTHOR)
            .where(AUTHOR.ID.eq(record.getId()))
            .fetchOne();
        assertThat(fromDb).isNotNull();
        assertThat(fromDb.getName()).isEqualTo(record.getName());
    }
    
    @Test
    void shouldCreateRecordWithExplicitValues() {
        // ACT: Create Author with explicit name
        AuthorRecord record = ctx.createRecord(AUTHOR)
            .set(AUTHOR.NAME, "J.R.R. Tolkien")
            .set(AUTHOR.COUNTRY, "England")
            .build();
        
        // ASSERT: Explicit values are used
        assertThat(record.getName()).isEqualTo("J.R.R. Tolkien");
        assertThat(record.getCountry()).isEqualTo("England");
    }
    
    @Test
    void shouldCreateRecordWithForeignKeyAutoCreation() {
        // ACT: Create Book (has FK to Author)
        BookRecord book = ctx.createRecord(BOOK).build();
        
        // ASSERT: Book is created
        assertThat(book).isNotNull();
        assertThat(book.getId()).isNotNull();
        assertThat(book.getTitle()).isNotNull();
        assertThat(book.getAuthorId()).isNotNull();
        
        // ASSERT: Author was automatically created
        AuthorRecord author = dsl.selectFrom(AUTHOR)
            .where(AUTHOR.ID.eq(book.getAuthorId()))
            .fetchOne();
        
        assertThat(author).isNotNull();
        assertThat(author.getName()).isNotNull();
    }
    
    @Test
    void shouldMixPojoAndRecordAPIs() {
        // ACT: Create Author as Record
        AuthorRecord authorRecord = ctx.createRecord(AUTHOR)
            .set(AUTHOR.NAME, "Isaac Asimov")
            .build();
        
        // ACT: Create Book as POJO, referencing Record-created Author
        var book = ctx.create(BOOK, 
                io.github.jtestkit.joot.test.fixtures.tables.pojos.Book.class)
            .set(BOOK.AUTHOR_ID, authorRecord.getId())
            .build();
        
        // ASSERT: Both work together
        assertThat(book.getAuthorId()).isEqualTo(authorRecord.getId());
        
        // Only one Author in DB
        assertThat(dsl.fetchCount(AUTHOR)).isEqualTo(1);
    }
}

