package integration;

import io.github.jtestkit.joot.JootContext;
import io.github.jtestkit.joot.test.fixtures.tables.pojos.Article;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static io.github.jtestkit.joot.test.fixtures.Tables.ARTICLE;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration tests for sequence/SERIAL support.
 * 
 * Tests that Joot correctly handles database-generated IDs:
 * - PostgreSQL SERIAL
 * - Sequences with DEFAULT
 * - Identity columns
 */
class SequenceSupportTest extends BaseIntegrationTest {
    
    private JootContext ctx;
    
    @BeforeEach
    void setup() {
        ctx = JootContext.create(dsl);
    }
    
    @Test
    void shouldCreateArticleWithSerialId() {
        // SERIAL = sequence-based auto-increment ID
        Article article = ctx.create(ARTICLE, Article.class).build();
        
        // ID should be generated by database
        assertThat(article).isNotNull();
        assertThat(article.getId()).isNotNull();
        assertThat(article.getId()).isPositive();
    }
    
    @Test
    void shouldGenerateSequentialIds() {
        // Create multiple articles
        Article article1 = ctx.create(ARTICLE, Article.class).build();
        Article article2 = ctx.create(ARTICLE, Article.class).build();
        Article article3 = ctx.create(ARTICLE, Article.class).build();
        
        // IDs should be sequential (or at least different)
        assertThat(article1.getId()).isNotNull();
        assertThat(article2.getId()).isNotNull();
        assertThat(article3.getId()).isNotNull();
        
        assertThat(article1.getId()).isNotEqualTo(article2.getId());
        assertThat(article2.getId()).isNotEqualTo(article3.getId());
        assertThat(article1.getId()).isNotEqualTo(article3.getId());
    }
    
    @Test
    void shouldRespectDefaultTimestamp() {
        // published_at has DEFAULT CURRENT_TIMESTAMP
        Article article = ctx.create(ARTICLE, Article.class).build();
        
        // Timestamp should be generated by database
        assertThat(article.getPublishedAt()).isNotNull();
    }
    
    @Test
    void shouldAllowExplicitIdOverride() {
        // User can still set explicit ID if needed
        Article article = ctx.create(ARTICLE, Article.class)
            .set(ARTICLE.ID, 999)
            .build();
        
        assertThat(article.getId()).isEqualTo(999);
    }
}

